/** All copy/strings for the Valentine experience */

export const PRE_QUESTION = "Aarvi, I have a question for you";

export const HEADLINE = "Will you be my Valentine?";

export const YES_LABEL = "Yes";
export const NO_LABEL = "No";

export const YES_CAPTION = "YAYAYAY I LOVE YOU SO MUCH CUTIEE💋💋💋";
export const YES_CAPTION_LINE2 = "I can't wait to meet you jaldi jaldi 💔💔";

export const TEASE_MESSAGES = [
  "wrong answer",
  "think about that again",
  "you sure about that?",
  "nah try again",
  "that's not very nice Aarvi",
  "ok but why though",
  "you're really trying huh",
  "come on now",
  "Aarvi please 😔",
  "just say yes it's not that hard",
  "i'm not giving up that easy",
  "you know you want to say yes",
  "the button won't let you either",
  "still no? seriously?",
  "you're making this way harder than it needs to be",
  "you're so stubborn",
  "just click yes already",
  "i promise it'll be worth it",
  "say yes or i'll be sad forever",
  "what did i ever do to you 😭",
  "you're actually breaking my heart rn",
  "imagine saying no to this sexy ahh face",
  "you're really testing me right now",
  "i'm literally right here",
  "just give up",
  "this is not very valentine's day of you",
  "that button doesn't even want to be clicked",
  "it's running from you too",
  "ok i see how it is",
  "fine. keep trying. i dare you.",
  "i have all day",
  "and all night",
  "and tomorrow too",
  "we can be here forever i don't care",
  "you're literally fighting a button right now",
  "and you're losing",
  "let that sink in",
  "a button is outsmarting you",
  "are you ok? like genuinely asking",
  "say yes and it stops running",
  "simple math",
  "i'm not running out of things to say",
  "i could do this all night",
  "you underestimate how stubborn i am",
  "that button is faster than you",
  "it always will be",
  "accept your fate",
  "your fate is saying yes btw",
  "to being my valentine",
  "which is obviously the right answer",
  "the only answer really",
  "there's no other option here",
  "see? it keeps running",
  "even the button knows the answer",
  "me and the button are on the same team",
  "the flowers agree too",
  "everyone's rooting for yes",
  "don't let us down",
  "you wouldn't. right?",
  "RIGHT?",
  "ok just… move the cursor… to yes",
  "it's right there",
  "yes isn't running away from you",
  "i literally made this whole thing for you",
  "the least you could do",
  "no pressure",
  "ok a little pressure",
  "a lot of pressure actually",
  "Aarvi come on",
  "i spent so long on this",
  "do you know how long this took me",
  "and you're out here clicking no",
  "unbelievable",
  "i'm not mad just disappointed",
  "ok maybe a little mad",
  "not really though",
  "because i know you'll say yes eventually",
  "everyone does",
  "well not everyone. just you hopefully.",
  "please? 🙏",
  "i'll take you to dinner",
  "wherever you want",
  "i'll even let you pick the movie",
  "that's a big deal and you know it",
  "ok i'm actually asking nicely now",
  "Aarvi will you please be my valentine",
  "the button is tired of running",
  "give it a break",
  "give me a break",
  "my heart can only take so much",
  "you're enjoying this aren't you",
  "i can tell you're smiling",
  "just say yes already",
  "you know this is inevitable",
  "why fight it",
  "the universe wants you to say yes",
  "i want you to say yes",
  "the button wants you to say yes",
  "unanimous decision honestly",
  "you're outvoted",
  "democracy has spoken",
  "say yes",
  "say yesssss",
  "please",
  "pretty please",
  "i'll stop bugging you if you say yes",
  "that's a lie i'll never stop",
  "but i'll be happy about it",
  "and you will too",
  "trust me on this one",
  "when have i ever been wrong",
  "don't answer that",
  "just click yes",
] as const;
